"""Write repro/requirements-lock.txt: every package of the research environment, pinned to its
exact version with the sha256 of every file published for that version (so pip can verify the
download on any platform with --require-hashes).

    FLY_PYTHON=<venv python> python repro/lock_env.py

Hashes come from the PyPI JSON API (metadata only; no package is downloaded).  flybrain is pinned
to the patched fork published in this repository's releases; torch (+cu126 builds) to the
PyTorch index.  Tools (pip, setuptools) are left out.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FLYBRAIN_URL = ("https://github.com/LxCenady/Fly-Is-All-You-Need/releases/download/flybrain-0.1.0.post1/"
                "flybrain-0.1.0.post1-py3-none-any.whl")
FLYBRAIN_SHA = "6c46867accf76b82e181bbe682e3f581e77d32e494d5c96fc135512e5e6b5d5c"
SKIP = {"pip", "setuptools"}


def get(url):
    with urllib.request.urlopen(url, timeout=60) as r:
        return r.read().decode()


def pypi_hashes(name, version):
    d = json.loads(get(f"https://pypi.org/pypi/{name}/{version}/json"))
    return sorted({u["digests"]["sha256"] for u in d["urls"]})


def torch_hashes(version):
    """sha256 of the published torch wheels for this local version (e.g. 2.14.0+cu126)."""
    local = version.split("+")[1]
    html = get(f"https://download.pytorch.org/whl/{local}/torch/")
    tag = version.replace("+", "%2B")
    return sorted(set(re.findall(rf"torch-{re.escape(tag)}-[^\"#]*#sha256=([0-9a-f]{{64}})", html)))


def main():
    py = os.environ.get("FLY_PYTHON") or sys.executable
    pkgs = json.loads(subprocess.run([py, "-m", "pip", "list", "--format=json"], capture_output=True, text=True).stdout)
    info = json.loads(subprocess.run([py, "-c", "import sys, platform; print(__import__('json').dumps("
                                          "[sys.version.split()[0], platform.platform()]))"],
                                     capture_output=True, text=True).stdout)
    lines = ["# Research environment, locked with hashes (generated by repro/lock_env.py).",
             f"# Recorded on: Python {info[0]}, {info[1]}, NVIDIA GPU with CUDA 12.",
             "# Install: python -m pip install --require-hashes -r repro/requirements-lock.txt",
             "#   (torch comes from the PyTorch index: add --extra-index-url https://download.pytorch.org/whl/cu126)",
             ""]
    missing = []
    for p in sorted(pkgs, key=lambda p: p["name"].lower()):
        name, ver = p["name"], p["version"]
        if name.lower() in SKIP:
            continue
        if name.lower() == "flybrain":
            lines.append(f"flybrain @ {FLYBRAIN_URL} \\\n    --hash=sha256:{FLYBRAIN_SHA}")
            continue
        try:
            hs = torch_hashes(ver) if name.lower() == "torch" and "+" in ver else pypi_hashes(name, ver)
        except Exception as e:                               # noqa: BLE001
            missing.append(f"{name}=={ver} ({e})"); continue
        if not hs:
            missing.append(f"{name}=={ver} (no hashes found)"); continue
        lines.append(f"{name}=={ver} \\\n" + " \\\n".join(f"    --hash=sha256:{h}" for h in hs))
        print(f"{name}=={ver}: {len(hs)} files", flush=True)
    if missing:
        lines += ["", "# Not locked (see ENVIRONMENT.md):"] + [f"#   {m}" for m in missing]
    (ROOT / "repro" / "requirements-lock.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("missing:", missing)


if __name__ == "__main__":
    main()
